-- MySQL Script generated by MySQL Workbench
-- 09/14/16 16:39:19
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema sql7133613
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema sql7133613
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `sql7133613` DEFAULT CHARACTER SET utf8 ;
USE `sql7133613` ;

-- -----------------------------------------------------
-- Table `sql7133613`.`user_type`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sql7133613`.`user_type` (
  `user_type_id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `user_type` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`user_type_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `sql7133613`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sql7133613`.`users` (
  `user_id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(10) NOT NULL,
  `password` VARCHAR(16) NOT NULL,
  `fk_user_type_id` INT(10) UNSIGNED NOT NULL,
  `fk_dentist_id` INT(10) UNSIGNED NULL DEFAULT NULL,
  `fk_lab_id` INT(10) UNSIGNED NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `address` VARCHAR(45) NULL DEFAULT NULL,
  `phone` VARCHAR(45) NULL DEFAULT NULL,
  `egn` VARCHAR(45) NULL DEFAULT NULL,
  `first_name` VARCHAR(45) NULL DEFAULT NULL,
  `last_name` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`user_id`, `username`),
  UNIQUE INDEX `idUsers_UNIQUE` (`user_id` ASC),
  UNIQUE INDEX `UserName_UNIQUE` (`username` ASC),
  INDEX `fk_Users_UsersType1_idx` (`fk_user_type_id` ASC),
  CONSTRAINT `fk_Users_UsersType1`
    FOREIGN KEY (`fk_user_type_id`)
    REFERENCES `sql7133613`.`user_type` (`user_type_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `sql7133613`.`laboratories`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sql7133613`.`laboratories` (
  `lab_id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `bulstat` VARCHAR(45) NOT NULL,
  `fk_manager_id` INT(10) UNSIGNED NOT NULL,
  `address` VARCHAR(70) NULL DEFAULT NULL,
  PRIMARY KEY (`lab_id`),
  UNIQUE INDEX `Bulstat_UNIQUE` (`bulstat` ASC),
  INDEX `fk_Lab_Manager_idx` (`fk_manager_id` ASC),
  CONSTRAINT `fk_Lab_Manager`
    FOREIGN KEY (`fk_manager_id`)
    REFERENCES `sql7133613`.`users` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `sql7133613`.`orders`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sql7133613`.`orders` (
  `order_id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `fk_dentist_id` INT(10) UNSIGNED NOT NULL,
  `fk_patient_id` INT(10) UNSIGNED NOT NULL,
  `fk_lab_id` INT(10) UNSIGNED NOT NULL,
  `date_enter` DATE NOT NULL,
  `price` DECIMAL(15,2) NOT NULL DEFAULT '0.00',
  PRIMARY KEY (`order_id`),
  UNIQUE INDEX `idOrders_UNIQUE` (`order_id` ASC),
  INDEX `fk_patient_id2_idx` (`fk_patient_id` ASC),
  INDEX `fk_dentist_users_id2_idx` (`fk_dentist_id` ASC),
  INDEX `fk_lab_id2_idx` (`fk_lab_id` ASC),
  CONSTRAINT `fk_dentist_users_id2`
    FOREIGN KEY (`fk_dentist_id`)
    REFERENCES `sql7133613`.`users` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_lab_id2`
    FOREIGN KEY (`fk_lab_id`)
    REFERENCES `sql7133613`.`laboratories` (`lab_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_patient_id2`
    FOREIGN KEY (`fk_patient_id`)
    REFERENCES `sql7133613`.`users` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `sql7133613`.`services`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sql7133613`.`services` (
  `services_id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `name_short` VARCHAR(10) NOT NULL,
  `name_long` VARCHAR(45) NULL DEFAULT NULL,
  `price` DECIMAL(7,2) NOT NULL DEFAULT '0.00',
  PRIMARY KEY (`services_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `sql7133613`.`services_in_order`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sql7133613`.`services_in_order` (
  `fk_order_id` INT(10) UNSIGNED NOT NULL,
  `fk_services_id` INT(10) UNSIGNED NOT NULL,
  `position` VARCHAR(2) NOT NULL,
  `color` VARCHAR(5) NOT NULL,
  INDEX `fk_services_id1_idx` (`fk_services_id` ASC),
  INDEX `fk_order_id1_idx` (`fk_order_id` ASC),
  CONSTRAINT `fk_order_id1`
    FOREIGN KEY (`fk_order_id`)
    REFERENCES `sql7133613`.`orders` (`order_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_services_id1`
    FOREIGN KEY (`fk_services_id`)
    REFERENCES `sql7133613`.`services` (`services_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
