-- MySQL Script generated by MySQL Workbench
-- 08/30/16 16:51:08
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema dentinfo
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `dentinfo` ;

-- -----------------------------------------------------
-- Schema dentinfo
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `dentinfo` DEFAULT CHARACTER SET utf8 ;
USE `dentinfo` ;

-- -----------------------------------------------------
-- Table `dentinfo`.`Services`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dentinfo`.`Services` ;

CREATE TABLE IF NOT EXISTS `dentinfo`.`Services` (
  `idServices` INT NOT NULL AUTO_INCREMENT,
  `ShortName` VARCHAR(10) NOT NULL,
  `FullName` VARCHAR(45) NOT NULL,
  `Price` DECIMAL(15,2) NOT NULL DEFAULT 0.00,
  PRIMARY KEY (`idServices`),
  UNIQUE INDEX `idServices_UNIQUE` (`idServices` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dentinfo`.`user_type`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dentinfo`.`user_type` ;

CREATE TABLE IF NOT EXISTS `dentinfo`.`user_type` (
  `user_type_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `user_type` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`user_type_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dentinfo`.`users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dentinfo`.`users` ;

CREATE TABLE IF NOT EXISTS `dentinfo`.`users` (
  `user_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(10) NOT NULL,
  `fk_user_type_id` INT UNSIGNED NOT NULL,
  `fk_dentist_id` INT UNSIGNED NULL,
  `fk_lab_id` INT UNSIGNED NULL,
  `password` VARCHAR(16) NULL,
  `email` VARCHAR(45) NOT NULL,
  `address` VARCHAR(45) NULL,
  `phone` VARCHAR(45) NULL,
  `egn` VARCHAR(45) NULL,
  `first_name` VARCHAR(45) NULL,
  `last_name` VARCHAR(45) NULL,
  PRIMARY KEY (`user_id`, `username`),
  UNIQUE INDEX `idUsers_UNIQUE` (`user_id` ASC),
  UNIQUE INDEX `UserName_UNIQUE` (`username` ASC),
  INDEX `fk_Users_UsersType1_idx` (`fk_user_type_id` ASC),
  CONSTRAINT `fk_Users_UsersType1`
    FOREIGN KEY (`fk_user_type_id`)
    REFERENCES `dentinfo`.`user_type` (`user_type_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dentinfo`.`laboratories`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dentinfo`.`laboratories` ;

CREATE TABLE IF NOT EXISTS `dentinfo`.`laboratories` (
  `lab_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `bulstat` VARCHAR(45) NOT NULL,
  `fk_manager_id` INT UNSIGNED NOT NULL,
  `address` VARCHAR(70) NULL,
  PRIMARY KEY (`lab_id`),
  UNIQUE INDEX `Bulstat_UNIQUE` (`bulstat` ASC),
  INDEX `fk_Lab_Manager_idx` (`fk_manager_id` ASC),
  CONSTRAINT `fk_Lab_Manager`
    FOREIGN KEY (`fk_manager_id`)
    REFERENCES `dentinfo`.`users` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dentinfo`.`orders`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dentinfo`.`orders` ;

CREATE TABLE IF NOT EXISTS `dentinfo`.`orders` (
  `order_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `fk_dentist_id` INT UNSIGNED NOT NULL,
  `fk_patient_id` INT UNSIGNED NOT NULL,
  `fk_lab_id` INT UNSIGNED NOT NULL,
  `date_enter` DATE NOT NULL,
  `price` DECIMAL(15,2) NOT NULL DEFAULT 0.00,
  PRIMARY KEY (`order_id`),
  UNIQUE INDEX `idOrders_UNIQUE` (`order_id` ASC),
  INDEX `fk_patient_id2_idx` (`fk_patient_id` ASC),
  INDEX `fk_dentist_users_id2_idx` (`fk_dentist_id` ASC),
  INDEX `fk_lab_id2_idx` (`fk_lab_id` ASC),
  CONSTRAINT `fk_patient_id2`
    FOREIGN KEY (`fk_patient_id`)
    REFERENCES `dentinfo`.`users` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_dentist_users_id2`
    FOREIGN KEY (`fk_dentist_id`)
    REFERENCES `dentinfo`.`users` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_lab_id2`
    FOREIGN KEY (`fk_lab_id`)
    REFERENCES `dentinfo`.`laboratories` (`lab_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dentinfo`.`services`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dentinfo`.`services` ;

CREATE TABLE IF NOT EXISTS `dentinfo`.`services` (
  `services_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name_short` VARCHAR(10) NOT NULL,
  `name_long` VARCHAR(45) NULL,
  `price` DECIMAL(7,2) NOT NULL DEFAULT 0.00,
  PRIMARY KEY (`services_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dentinfo`.`services_in_order`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dentinfo`.`services_in_order` ;

CREATE TABLE IF NOT EXISTS `dentinfo`.`services_in_order` (
  `fk_order_id` INT UNSIGNED NOT NULL,
  `fk_services_id` INT UNSIGNED NOT NULL,
  `position` VARCHAR(2) NOT NULL,
  `color` VARCHAR(5) NOT NULL,
  INDEX `fk_services_id1_idx` (`fk_services_id` ASC),
  INDEX `fk_order_id1_idx` (`fk_order_id` ASC),
  CONSTRAINT `fk_services_id1`
    FOREIGN KEY (`fk_services_id`)
    REFERENCES `dentinfo`.`services` (`services_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_order_id1`
    FOREIGN KEY (`fk_order_id`)
    REFERENCES `dentinfo`.`orders` (`order_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
